### ISSUE TITLE
To-do items from reviewing

### ISSUE THREAD

**Issue by hardin47** [OpenIntroStat/ims#80]
- [x] I'd like to replace "data matrix" with "data frame".  How do you feel about that?  I'm wary of the word matrix.
- [x] Figure 1.1, I’d swap the box order (to align with how the material is presented), how hard is that?
- [x] Do we need to introduce the email dataset?  Or at least link to it? In an Example in section 4.3 (Table 4.5 should at least have a footnote to the package, right?)
- [x] Chapter 16:  add a full citation / reference to the malaria study
- [x] Section 8.3.1, what are the “types” of outliers?  It seems like we should clearly specify the options.  Some of the exercises ask to name which type of outlier it is.
- [x] Figure 8.16 needs slightly bigger xlim and ylim for the circles around the points.
- [x] The paragraph that starts “Examine the residual plots in 8.16 and 8.17…”  it isn’t clear why “CDE”, do you know why the text says CDE?
- [x] 8.1.4 add an example where the data are in inches and lbs and get transformed to cm and kg, thus showing that the labelling changes but the linear trend does not change.
- [x]  section 14.1.2, there are three examples that are “better with normality”, but I don’t think they are.  And we do randomization/ bootstrapping in those exact settings (??!??).  Maybe we can just remove the phrase that says "constructing suitable simulations can be difficult."

**Comment by mine-cetinkaya-rundel** [comment]
For “Examine the residual plots in 8.16 and 8.17…” -- plots C, D, and E have influential points. Should we make that more clear then?

**Comment by mine-cetinkaya-rundel** [comment]
In C, D, and E, You will probably find that there are a few observations which are not in the trajectory of the trend in the rest of the data.

Also clarify what this means in terms of leverage -- points are away from the bounds of the x for the rest of the data.
